name: Daily Market Report
on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'  # 7:30 AM EST (11:30 UTC)

jobs:
  generate_report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python Dependencies
        run: |
          pip install yfinance pandas yagmail pytz requests bs4
      
      - name: Run Market Report
        run: |
          python market_report.py
